package org.muni.fi;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SQLServerDB implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    private Connection connection = null;
    
    public Integer insertReservation (Reservation reservation)
    {
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

        try
        {
            String SQL = "INSERT INTO reservations(start, finish, people, email) VALUES ('"
                    + dateFormat.format(reservation.getStart())
                    + "', '" + dateFormat.format(reservation.getEnd()) + "', "
                    + reservation.getPeople() + ", '" + reservation.getEmail() + "');";
            Statement statement = connection.createStatement();
            Integer result = statement.executeUpdate(SQL);

            return  result;
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }

        return -2;
    }

    public SQLServerDB()
    {
        try
        {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            String connectionUrl = "jdbc:sqlserver://localhost;instanceName=SQLEXPRESS;databaseName=idrink;user=sa;password=*****";
            connection = DriverManager.getConnection(connectionUrl);
        }
        catch (Exception ex)
        {
            System.out.println(ex.getMessage());
        }
    }

}